geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/login/google-oauth2/',
         include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(
    #     settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from pathlib import PurePath
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.MainView.as_view(), name='main'),
    path('products/', mainapp.ProductList.as_view(), name='products'),
    path('products/category/<int:pk>/',
         mainapp.ProductList.as_view(), name='products_category'),
    path('product/<int:pk>/', mainapp.ProductDetail.as_view(), name='detail'),
]

geekshop/ordersapp/urls.py
from django.urls import path
from pathlib import PurePath
import ordersapp.views as views
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('list/', views.OrderList.as_view(), name='list'),
    path('create/', views.OrderItemsCreate.as_view(), name='create'),
    path('update/<int:pk>/',
         views.OrderStatusUpdate.as_view(), name='status_update'),
    path('update/<int:pk>/items/',
         views.OrderItemsUpdate.as_view(), name='items_update'),
    path('item/get/price/<int:pk>/',
         views.FetchOrderItemPrice.as_view(), name='get_price'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name='detail'),
    path('delete/order/<int:pk>/', views.OrderDelete.as_view(), name='delete'),
    path('delete/item/<int:pk>/',
         views.OrderItemDelete.as_view(), name='item_delete'),
]

geekshop/ordersapp/models.py
from django.db import models
from django.db.models import F
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from mainapp.models import CoreManager, CoreQuerySet, Core, Product
from geekshop.settings import AUTH_USER_MODEL

# Create your models here.


class Order(Core):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, _('forming')),
        (SENT_TO_PROCEED, _('send to proceed')),
        (PAID, _('paid')),
        (PROCEEDED, _('proceeded')),
        (READY, _('ready')),
        (CANCEL, _('cancel')),
    )

    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('updated'), auto_now=True)
    status = models.CharField(_('status'), max_length=3,
                              choices=ORDER_STATUS_CHOICES, default=FORMING)
    title = None

    class Meta:
        ordering = ('-created',)
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    def __str__(self):
        return 'Order {}, created {}'.format(self.id, self.created)

    def get_absolute_url(self):
        return reverse_lazy('ordersapp:list')

    def delete(self):
        self.order_items.delete()
        self.active = False
        self.save()
        super().delete()

    @property
    def total_items_quantity(self):
        return self.order_items.count()

    @property
    def total_quantity(self):
        return sum([item.quantity for item in self.order_items.all()])

    @property
    def total_price(self):
        return sum([item.price for item in self.order_items.all()])


class OrderItemQueryset(CoreQuerySet):
    """Re-define 'delete' method"""

    def delete(self):
        for object in self:
            object.delete()
        super().delete()


class OrderItemManager(CoreManager):
    """
    Re-define 'get_queryset' method (assign new custom queryset) + define
    'delete' method, that call queryset's 'delete'
    """

    def get_queryset(self):
        return OrderItemQueryset(self.model).filter(active=True, deleted=False)

    def delete(self):
        return self.get_queryset().delete()


class OrderItem(Core):
    order = models.ForeignKey(
        Order, related_name="order_items", on_delete=models.CASCADE)
    item = models.ForeignKey(
        Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(_('quantity'), default=0)
    title = None

    objects = OrderItemManager()

    def __str__(self):
        return 'id {}, item - {}'.format(self.id, self.item)

    def save(self, **kwargs):

        if self.pk:
            self.item.quantity = F('quantity') - self.quantity + \
                self._meta.model.objects.get(pk=self.pk).quantity
        else:
            self.item.quantity = F('quantity') - self.quantity

        self.item.save()
        super().save()

    def delete(self):
        self.item.quantity += self.quantity
        self.item.save()
        super().delete()

    @property
    def price(self):
        return self.item.price * self.quantity

geekshop/ordersapp/forms.py
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm, inlineformset_factory
from django import forms

from .models import Order, OrderItem
from accounts.forms import ChangeWidgetMixin


class OrderForm(ChangeWidgetMixin, ModelForm):

    class Meta:
        model = Order
        exclude = ('user',)


class OrderItemForm(ChangeWidgetMixin, ModelForm):
    price = forms.CharField(label=_('price'), required=False)

    class Meta:
        model = OrderItem
        fields = ('item', 'quantity')


OrderFormset = inlineformset_factory(
    Order, OrderItem, form=OrderItemForm, can_delete=False, extra=1)

geekshop/ordersapp/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic import DetailView, View
from django.views.generic.detail import SingleObjectMixin
from django.db import transaction
# from django.utils.translation import ugettext_lazy as _
# from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse
# from django.shortcuts import redirect
from .models import *
from .forms import *

# Create your views here.


class OrderList(LoginRequiredMixin, ListView):
    """Class lists all orders in template"""

    model = Order

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class OrderDetail(LoginRequiredMixin, DetailView):
    """Renders detail info of significant order"""

    model = Order

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related('order_items__item')
        return queryset


class OrderStatusUpdate(LoginRequiredMixin, UpdateView):
    """Updates status when click on 'buy' in '_detail' template"""

    model = Order
    fields = ('status',)

    def get(self, request, **kwargs):
        return self.post(request, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'data': {'status': self.object.SENT_TO_PROCEED}})
        return kwargs


class OrderDelete(LoginRequiredMixin, DeleteView):
    """Class for deleting order"""

    model = Order
    success_url = reverse_lazy('ordersapp:list')

    def get(self, request, **kwargs):
        return self.post(request, **kwargs)


class OrderItemsFormsetMixin():
    """Mixin sets same attributes for classes"""

    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')

    def dispatch(self, request, **kwargs):

        if self.kwargs.get('pk'):
            obj = self.get_object()
            self.items = obj.order_items
            instance = obj
        else:
            self.items = self.request.user.get_card.get_items
            instance = None

        if self.request.method == 'POST':
            self.formset = OrderFormset(self.request.POST, instance=instance)
        else:
            self.formset = OrderFormset(instance=instance)

        return super().dispatch(request, **kwargs)


class OrderItemsCreate(LoginRequiredMixin, OrderItemsFormsetMixin, CreateView):
    """Class for creating order with items"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.request.method == 'POST':
            if self.items:
                self.formset.extra = self.items.count()
                for num, form in enumerate(self.formset.forms):
                    form.initial = {
                        'item': self.items.all()[num].item,
                        'quantity': self.items.all()[num].quantity,
                        'price': self.items.all()[num].price
                    }

        context.update({'formset': self.formset})
        return context

    def form_valid(self, form):
        formset = self.formset

        with transaction.atomic():
            form.instance.user = self.request.user
            response = super().form_valid(form)

            if formset.is_valid():
                formset.instance = self.object
                formset.save()

            self.items._hints.get('instance').delete()
            if not self.object.total_items_quantity:
                self.object.delete()
            return response


class OrderItemsUpdate(LoginRequiredMixin, OrderItemsFormsetMixin, UpdateView):
    """Update order items in order"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # receive ids for all products in order and set queryset for extra formset's item field
        ids = Product.objects.exclude(
            id__in=self.object.order_items.values_list('item_id', flat=True))
        self.formset.forms[-1].fields['item'].queryset = ids

        for form in self.formset.forms:
            if form.instance.pk:
                form.initial['price'] = form.instance.item.price

        context.update({'formset': self.formset})
        return context

    def form_valid(self, form):
        formset = self.formset

        with transaction.atomic():
            response = super().form_valid(form)

            if formset.is_valid():
                formset.save()

            if not self.object.total_items_quantity:
                self.object.delete()

            return response


class FetchOrderItemPrice(LoginRequiredMixin, SingleObjectMixin, View):
    """Class that fetch price of order item's product with ajax request"""

    model = Product

    def get(self, request, **kwargs):
        if self.request.is_ajax():
            data = {'price': self.get_object().price}
            return JsonResponse(data)


class OrderItemDelete(LoginRequiredMixin, DeleteView):
    """Class for deleting order item"""

    model = OrderItem
    success_url = reverse_lazy('ordersapp:list')

    def get(self, request, **kwargs):
        return self.post(request, **kwargs)

    def post(self, request, **kwargs):
        order = self.get_object().order
        response = super().post(request, **kwargs)
        if not order.order_items.all():
            order.delete()
        return response

geekshop/ordersapp/templates/ordersapp/order_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Order #' %}{{ object.id }}
{% endblock %}

{% block data %}
    {% include 'ordersapp/includes/inc_order_info.html' %}
    <div class="order_detail">
        <div class="table_header">
            <p>{% trans 'Image' %}</p>
            <p>{% trans 'Title' %}</p>
            <p>{% trans 'Quantity' %}</p>
            <p>{% trans 'Price' %}</p>
        </div>
        {% for object in object.order_items.all %}
            <div class="order_detail_item">
                <div class="order_item_pic">
                    <img src="{{ object.item.pictures.all.0.picture.url }}" alt="{{ object.item.creator }}">
                </div>
                <div class="order_detail_item_data">
                    <p>{{ object.item.creator }}</p>
                    <p>{{ object.item.title }}</p>
                </div>
                <p>{{ object.quantity }} {% trans 'pc' %}</p>
                <p>&#8381; {{ object.price|floatformat }}</p>
            </div>
        {% endfor %}
        <div class="order_detail_buttons">
            {% if object.status == 'FM' %}
                <a class="btn btn-secondary" href="{% url 'ordersapp:status_update' object.id %}" >{% trans 'Buy' %}</a>
                <a class="btn btn-secondary" href="{% url 'ordersapp:items_update' object.id %}">{% trans 'Edit' %}</a>
                <a class="btn btn-secondary" href="{% url 'ordersapp:delete' object.id %}">{% trans 'Delete' %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends 'base.html' %}
{% load static i18n %}
{% load cache %}

{% block javascript %}
    <script src="{% static 'ordersapp/js/jquery.formset.js' %}"></script>
    <script src="{% static 'ordersapp/js/order_scripts.js' %}"></script>
{% endblock %}

{% block title %}
    {% trans 'Order' %}
{% endblock %}

{% block data %}

    {% include 'ordersapp/includes/inc_order_info.html' %}
    <form class="order_items" action="#" method="post">
        {% csrf_token %}
        {{ form }}
        {{ formset.management_form }}
        {% for form in formset.forms %}
            {{ field.errors.as_ul }}
            <div class="order_item">
                {% for field in form %}
                    {% if field.name != 'price' %}
                        {{ field }}
                    {% else %}
                        {% if field.value %}
                            <p class="price">{{ field.value|floatformat }}</p>
                        {% else %}
                            <p class="price">0</p>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                {% if form.instance.pk %}
                    <a href="{% url 'ordersapp:item_delete' form.instance.pk %}" class="btn btn-secondary">{% trans 'Delete' %}</a>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-secondary">
            {% if request.resolver_match.url_name == 'items_update' %}
                {% trans 'Save' %}
            {% else %}
                {% trans 'Create' %}
            {% endif %}
        </button>
    </form>


{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Your orders' %}
{% endblock %}

{% block data %}

    <div class="orders">
        <p>{% trans 'Your orders' %}</p>
        {% if object_list %}
            <div class="table_title">
                <p>{% trans 'Id' %}</p>
                <p>{% trans 'Created' %}</p>
                <p>{% trans 'Updated' %}</p>
                <p>{% trans 'Status' %}</p>
                <p>{% trans 'Actions' %}</p>
            </div>
            {% for object in object_list %}
                <div class="order_row">
                    <p>{{ object.id }}</p>
                    <p>{{ object.created|date:'Y-m-d H:i:s' }}</p>
                    <p>{{ object.updated|date:'Y-m-d H:i:s' }}</p>
                    <p>{{ object.get_status_display }}</p>
                    <div class="buttons">
                        <a href="{% url 'ordersapp:detail' object.id %}" class="btn btn-secondary">{% trans 'Detail' %}</a>
                        {% if object.status == 'FM' %}
                            <a href="{% url 'ordersapp:delete' object.id %}" class="btn btn-secondary">{% trans 'Delete' %}</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>{% trans 'You have not orders yet.' %}</p>
        {% endif %}
    </div>

{% endblock %}