geekshop/accounts/urls.py
from django.urls import path
from accounts import views
from pathlib import PurePath
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='registration'),
    path('register/confirm/',
         views.RegistrationConfirm.as_view(), name='confirm'),
    path('verify/<str:username>/<str:key>/',
         views.VerifyEmail.as_view(), name='verify'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    path('update/', views.UserUpdateView.as_view(), name='update'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/login/google-oauth2/',
         include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(
    #     settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from pathlib import PurePath
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.MainView.as_view(), name='main'),
    path('products/', mainapp.ProductList.as_view(), name='products'),
    path('products/category/<int:pk>/',
         mainapp.ProductList.as_view(), name='products_category'),
    path('product/<int:pk>/', mainapp.ProductDetail.as_view(), name='detail'),
]

geekshop/accounts/models.py
from django.db import models, transaction
from django.urls import reverse_lazy
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now, timedelta
from django.utils.functional import cached_property

from .utils import key_hasher, send_message

# Create your models here.


class User(AbstractUser):
    """Class represent user table in db"""

    # age = models.PositiveIntegerField(_('age'))
    age = models.PositiveIntegerField(_('age'), default=18)
    avatar = models.ImageField(
        _('avatar'), upload_to='media/images', max_length=250, blank=True)
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(
        default=(now() + timedelta(hours=48)))

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def save(self, *args, **kwargs):
        if not self.id:
            with transaction.atomic():
                super().save(*args, **kwargs)
                UserProfile.objects.create(user=self)
        else:
            super().save(*args, **kwargs)

    def is_activation_key_not_expired(self):
        return now() <= self.activation_key_expires

    def reset_activation_key(self):
        self.activation_key = key_hasher(self.email)
        self.activation_key_expires = now() + timedelta(hours=48)
        self.save()
        return send_message(self)

    def get_absolute_url(self):
        return reverse_lazy('mainapp:main')

    @cached_property
    def get_card(self):
        return self.basket.last()


class UserProfile(models.Model):
    """Class represent userprofile as one-to-one field to User model"""

    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, _('Male')),
        (FEMALE, _('Female')),
    )

    user = models.OneToOneField(
        User, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    gender = models.CharField(
        _('gender'), max_length=1, choices=GENDER_CHOICES, blank=True)
    tag = models.CharField(_('tags'), max_length=128, blank=True)
    about = models.TextField(_('about'), max_length=512, blank=True)

geekshop/accounts/forms.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm, UserChangeForm
    )
from django.forms import ValidationError, ModelForm
from .models import User, UserProfile
import random
import hashlib


class ChangeWidgetMixin:
    """Mixin for change widgets attributes"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].help_text = ''


class LoginForm(ChangeWidgetMixin, AuthenticationForm):
    """Form for user login"""

    class Meta:
        model = User
        fields = ('username', 'password')


class UserForm(ChangeWidgetMixin, UserCreationForm):
    """Form class for user creation"""

    class Meta:
        model = User
        fields = ('username', 'first_name',
                  'last_name', 'age', 'email', 'avatar')

    def clean_age(self):
        age = self.cleaned_data['age']
        if age < 18:
            raise ValidationError(_('You are very young!'))
        return age

    def save(self):
        user = super().save()
        user.is_active = False
        salt = hashlib.sha1(
            str(random.random()).encode('utf-8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1(
            (user.email + salt).encode('utf-8')).hexdigest()
        user.save()
        return user


class UserChangeForm(ChangeWidgetMixin, UserChangeForm):
    """Form class for updaiting user data"""

    class Meta:
        model = User
        fields = ('username', 'first_name',
                  'last_name', 'age', 'email', 'avatar')

    def clean_age(self):
        return UserForm.clean_age(self)


class UserProfileUpdateForm(ChangeWidgetMixin, ModelForm):
    """Form class for updating userprofile data"""

    class Meta:
        model = UserProfile
        fields = ('gender', 'tag', 'about')

geekshop/accounts/views.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic.edit import SingleObjectMixin, UpdateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.db import transaction

from .models import User
from .forms import UserForm, UserChangeForm, UserProfileUpdateForm, LoginForm
from .utils import send_message


# Create your views here.

class UserLogin(UserPassesTestMixin, LoginView):
    """Class for user login"""

    success_url = reverse_lazy('mainapp:main')
    form_class = LoginForm

    def test_func(self):
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        return redirect(self.success_url)


class UserLogout(LogoutView):
    """Class for user logout"""

    success_message = _('You are logged out!')

    def get_next_page(self):
        next_page = super().get_next_page()
        if next_page:
            messages.success(self.request, self.success_message)
        return next_page


class UserCreateView(CreateView):
    """Class create new user in db"""

    model = User
    form_class = UserForm

    def get_success_url(self):
        return reverse_lazy('accounts:confirm')

    def form_valid(self, form):
        response = super().form_valid(form)
        if send_message(self.object):
            messages.success(self.request, _(
                'Activation message was sent succefully!'))
        else:
            messages.error(
                self.request, _(
                    'Activation message was not sent.'
                    'Please, contact with administrator.'
                    )
            )
        return response


class RegistrationConfirm(TemplateView):
    """Class for information user about registration"""

    template_name = 'accounts/registration_confirm.html'


class VerifyEmail(SingleObjectMixin, TemplateView):
    """Class for activation user by activation key"""

    model = User
    template_name = 'accounts/verify_email.html'

    def get_object(self):
        username = self.kwargs.get('username')
        obj = get_object_or_404(self.model, username=username)
        return obj

    def get_context_data(self, *args, **kwargs):
        self.object = self.get_object()
        return super().get_context_data(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        key = self.kwargs.get('key')
        if not self.object.is_active:
            if key == self.object.activation_key and \
                    self.object.is_activation_key_not_expired:
                self.object.is_active = True
                # self.object.activation_key = ''
                self.object.save()
                messages.success(self.request, _('confirmed'))
            else:
                if self.object.reset_activation_key():
                    messages.warning(self.request, _(
                        'Activation message was resent succefully!'))
                else:
                    messages.error(
                        self.request, _(
                            'Activation message was not sent'
                            'Please, contact with administrator.'
                            )
                        )
        else:
            messages.info(self.request, _('User is already activated!'))

        return response


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Class for updating user and userprofile data"""

    form_class = UserChangeForm
    template_name_suffix = '_update'

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'profile_form': UserProfileUpdateForm(
            instance=self.object.userprofile)})
        return context

    def form_valid(self, form):
        with transaction.atomic():
            profile_form = UserProfileUpdateForm(
                self.request.POST, instance=self.object.userprofile)
            if profile_form.is_valid():
                profile_form.save()
                return super().form_valid(form)

geekshop/accounts/templates/accounts/registration_confirm.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Confirmation' %}
{% endblock %}

{% block data %}
    <div class="center">
        <div class="user-form">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <p>{{ message }}</p>
                    {% elif message.tags == 'error' %}
                        <p>{{ message }}</p>
                        <div class="user-form">
                            <form action="{% url 'mainapp:main' %}">
                                <label for="email">{% trans 'Your email' %}</label>
                                <input id="email" type="email" class="form-control">
                                <label for="message">{% trans 'Your message' %}</label>
                                <textarea id="message" type="textarea" rows="4" cols="50" class="form-control" name="#"></textarea>
                                <button type="submit" class="btn btn-secondary">{% trans 'Send' %}</button>
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>{% trans 'This page made for confirmation of user registration.' %}</p>
                <p>{% trans 'Not for games.' %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

geekshop/accounts/templates/accounts/user_form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Registration' %}
{% endblock %}

{% block data %}
    <div class="center">
        <div class="user-form">
            <form action="#" method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-secondary">{% trans 'Save' %}</button> 
            </form>
        </div>
    </div>
{% endblock %}

geekshop/accounts/templates/accounts/user_update.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Update user data' %}
{% endblock %}

{% block data %}
    <div class="center">
        <div class="user-form">
            <form action="#" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    {{ profile_form }}
                <button type="submit" class="btn btn-secondary">{% trans 'Save' %}</button> 
            </form>
        </div>
    </div>
{% endblock %}

geekshop/accounts/templates/accounts/verify_email.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
    {% trans 'Verify account' %}
{% endblock %}

{% block data %}
    <div class="center">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <p>{% trans 'Your account was ' %}{{ message }} {% trans ' successfully.' %}</p>
                    <p>
                        {% trans 'Now, you can ' %}
                        <a href="{% url 'accounts:login' %}">
                        {% trans 'login' %}</a>
                        {% trans 'into system.' %}
                    </p>
                {% elif message.tags == 'warning' %}
                    <p>{% trans 'Your activation key has expired or key is wrong.' %}</p>
                    <p>{{ message }}</p>
                    <p>{% trans 'Please, check your mail.' %}</p>
                    <a href="{% url 'mainapp:main' %}">{% trans 'Go to main page.' %}</a>
                {% elif message.tags == 'error' %}
                    <p>{{ message }}</p>
                    <div class="user-form">
                        <form action="{% url 'mainapp:main' %}">
                            <label for="email">{% trans 'Your email' %}</label>
                            <input id="email" type="email" class="form-control">
                            <label for="message">{% trans 'Your message' %}</label>
                            <textarea id="message" type="textarea" rows="4" cols="50" class="form-control" name="#"></textarea>
                            <button type="submit" class="btn btn-secondary">{% trans 'Send' %}</button>
                        </form>
                    </div>
                {% elif message.tags == 'info' %}
                    <p>{{ message }}</p>
                    <a href="{% url 'mainapp:main' %}">{% trans 'Go to main page.' %}</a>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}