geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/login/google-oauth2/',
         include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(
    #     settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from pathlib import PurePath
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.MainView.as_view(), name='main'),
    path('products/', mainapp.ProductList.as_view(), name='products'),
    path('products/category/<int:pk>/',
         mainapp.ProductList.as_view(), name='products_category'),
    path('product/<int:pk>/', mainapp.ProductDetail.as_view(), name='detail'),
]

geekshop/mainapp/models.py
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse_lazy
from django.core.validators import MaxValueValidator

# Create your models here.


class CoreQuerySet(models.QuerySet):
    """Custom queryset class, realization soft delete for QuerySet"""

    def delete(self):
        return super(CoreQuerySet, self).update(deleted=True, active=False)

    def hard_delete(self):
        return super(CoreQuerySet, self).delete()


class CoreManager(models.Manager):
    """Change initial QuerySet and queryset for superuser in admin panel"""

    def get_queryset(self):
        return CoreQuerySet(self.model).filter(active=True, deleted=False)

    def get_all_queryset(self):
        return CoreQuerySet(self.model)


class Core(models.Model):
    """Core abstract class"""

    title = models.CharField(_('title'), max_length=250, unique=True)
    description = models.TextField(_('description'), blank=True)
    sort = models.IntegerField(_('sort'), default=0, null=True, blank=True)
    active = models.BooleanField(_('active'), default=True)
    deleted = models.BooleanField(_('deleted'), default=False)

    objects = CoreManager()
    all_objects = models.Manager()

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    @property
    def verbose_name(self):
        return self._meta.verbose_name

    @property
    def verbose_name_plural(self):
        return self._meta.verbose_name_plural

    def delete(self):
        self.deleted = True
        self.active = False
        self.save()

    def hard_delete(self):
        self.delete()


class Category(Core):
    """Class represents category table in db"""

    kind = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE)
    discount = models.PositiveIntegerField(
        _('discount'), validators=[MaxValueValidator(70)], default=0)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def save(self, **kwargs):
        with transaction.atomic():
            if self.product_set:
                self.product_set.update(discount=self.discount)
            super().save(**kwargs)

    def delete(self):
        with transaction.atomic():
            self.product_set.all().delete()
            super().delete()


class Manufacturer(Core):
    """Class represent manufacturer table in db"""

    class Meta:
        verbose_name = _('Manufacturer')
        verbose_name_plural = _('Manufacturers')


class Product(Core):
    """Class represent product table in db"""

    men = 'M'
    women = 'W'

    gender_choices = (
        (men, 'Men'),
        (women, 'Women'),
    )

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    creator = models.ForeignKey(
        Manufacturer, null=True, blank=True, on_delete=models.SET_NULL)
    price = models.DecimalField(
        _('Price'), max_digits=8, decimal_places=2, default=0, blank=True)
    discount = models.PositiveIntegerField(
        _('discount, %'), validators=[MaxValueValidator(70)], default=0)
    quantity = models.PositiveIntegerField(
        _('Quantity on stock'), default=0, blank=True)
    gender = models.CharField(
        _('gender'), max_length=1, choices=gender_choices, default=men)

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ['id']

    def get_absolute_url(self):
        return reverse_lazy('mainapp:detail', kwargs={'pk': self.id})

    @property
    def discount_price(self):
        return self.price - (self.price * self.discount / 100)

    def __str__(self):
        return '{} {}'.format(self.title, self.category.title)


class Image(Core):
    """Class represent image table in db"""

    picture = models.ImageField(
        _('picture'), upload_to='media/images', max_length=250)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='pictures')

    class Meta:
        verbose_name = _('Picture')
        verbose_name_plural = _('Pictures')
        ordering = ['id']

geekshop/mainapp/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from accounts.forms import ChangeWidgetMixin


class AddBasketItemForm(ChangeWidgetMixin, forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=20)

    def __init__(self, product, *args, **kwargs):
        self.product = product
        return super().__init__(**kwargs)

    def clean_quantity(self):
        clean_quantity = self.cleaned_data.get('quantity')
        if not clean_quantity <= self.product.quantity:
            raise forms.ValidationError(
                _('Entered quantity greater than stock quantity!'))
        return clean_quantity

geekshop/mainapp/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.conf import settings
from django.core.cache import cache

from .models import Product
from .forms import AddBasketItemForm
from basketapp.views import BasketUpdate

# Create your views here.


class MainView(ListView):
    """Class process main page"""

    model = Product
    ordering = ['?']
    template_name = 'mainapp/index.html'

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related(
            'pictures').select_related('creator')
        return queryset


class ProductList(ListView):
    """Class process catalogue page"""

    model = Product
    paginated_by = 8
    columns = 2
    orphans = 0

    def get(self, request, **kwargs):
        response = super().get(request, **kwargs)

        if self.request.is_ajax():
            result = render_to_string(
                'mainapp/includes/inc_product_list.html',
                context=self.get_context_data(),
                request=self.request
            )
            return JsonResponse({'result': result})
        else:
            return response

    def get_queryset(self):
        queryset = super().get_queryset().select_related(
            'creator', 'category').prefetch_related('pictures')
        if 'pk' in self.kwargs:
            queryset = queryset.filter(category=self.kwargs.get('pk'))
        return queryset

    def get_paginated_rows(self, dataset):
        paginator = self.paginator_class(dataset, self.columns, self.orphans)
        for page_num in paginator.page_range:
            yield paginator.page(page_num).object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            categories=self.get_categories(), **kwargs)
        context.update(
            {'obj_pages':
                [row for row in self.get_paginated_rows(self.object_list)]})
        return context

    # this is for cache testing
    # if you want check how it works add cache_page(3600) to this view
    # in urls.py
    def get_categories(self):
        if settings.LOW_CACHE:
            key = 'categories'
            categories = cache.get(key)
            if categories is None:
                categories = self.model.category.get_queryset()
                cache.set(key, categories)
            return categories
        else:
            return self.model.category.get_queryset()


class ProductDetail(LoginRequiredMixin, FormView, DetailView):
    """Class process page with detail info about product"""

    model = Product
    form_class = AddBasketItemForm

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        if request.is_ajax():
            result = render_to_string(
                'mainapp/includes/inc_product_detail_ajax.html',
                context=self.get_context_data(),
                request=request
            )
            return JsonResponse({'result': result})
        else:
            return response

    def get_queryset(self):
        return super().get_queryset().select_related(
            'category', 'creator').prefetch_related('pictures')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        similar = self.get_queryset().exclude(
            id=self.object.id).filter(
                category=self.object.category).order_by('?')
        context.update({'similar': similar})
        return context

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs.update({'product': self.object})
        return kwargs

    def post(self, request, **kwargs):
        self.object = self.get_object()
        response = super().post(request, **kwargs)

        if request.is_ajax():
            self.object.refresh_from_db()
            card = request.user.basket.last()
            summary = card.get_summary

            data = {
                'price': summary['total_price'],
                'card_quantity': summary['total_items_quantity'],
                'product_quantity': self.object.quantity
            }

            if self.object.quantity == 0:
                html = render_to_string(
                    'mainapp/includes/inc_product_not_exists.html',
                    context=self.get_context_data(),
                    request=request
                )
                data.update({'html': html})

            return JsonResponse(data)

        return response

    def form_valid(self, form):
        self.kwargs.update({'quantity': form.cleaned_data.get('quantity')})
        return BasketUpdate.as_view()(self.request, *self.args, **self.kwargs)

geekshop/mainapp/templates/mainapp/includes/inc_index_products.html
{% load static i18n %}

<div class="index-page-pictures">
    {% if range %}
        {% for object in object_list|slice:range %}
            {% include 'mainapp/includes/inc_picture_block.html' %}
        {% empty %}
            <p>{% trans 'Sorry, the list of products is empty!' %}</p>
        {% endfor %}
    {% else %}
        {% for object in object_list %}
            {% include 'mainapp/includes/inc_picture_block.html' %}
        {% empty %}
            <p>{% trans 'Sorry, the list of products is empty!' %}</p>
        {% endfor %}
    {% endif %}
</div> 

geekshop/mainapp/templates/mainapp/includes/inc_picture_block.html
{% load i18n %}

<div class="index-page-pictures-block">
    <div class="picture">
        <img src="{{ object.pictures.all.0.picture.url }}" alt="{{ object.title }}">
        <a href="{{ object.get_absolute_url }}">{% trans 'Detail view'|upper %}</a>
    </div>
    <p>{{ object.creator }} {{ object.title }}</p>
    <p>&#8381; {{ object.discount_price|floatformat }}</p>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_product_detail_ajax.html
{% load static i18n %}

<div class="product-pictures">
    <div class="hero-picture">
        <img src="{{ object.pictures.all.0.picture.url }}" alt="{{ object.title }}">
    </div>
    {% if similar %}
        <p>{% trans 'Similar products' %}</p>
        <div class="similar-pictures">
            {% for product in similar|slice:":3" %}
                <div class="sim-pic">
                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.pictures.all.0.picture.url }}" alt="{{ product.title }}"></a>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
<div class="product-data">
    <p>{% trans 'Manufacturer: ' %}<span>{{ object.creator }}</span></p>
    <p>{% trans 'Title: ' %}<span>{{ object.title }}</span></p>
    <p>{% trans 'Category: ' %}<span>{{ object.category }}</span></p>
    <p class='prod_quantity'>{% trans 'Quantity on stock: ' %}<span>{{ object.quantity }}</span></p>
    <p>{% trans 'Price: ' %}<span>&#8381; {{ object.discount_price|floatformat }}</span></p>
    {% if object.quantity == 0 %}
      {% include 'mainapp/includes/inc_product_not_exists.html' %}
    {% else %}
        <form action="#" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-secondary">{% trans 'Add to cart' %}</button>
        </form>
    {% endif %}
</div>

geekshop/mainapp/templates/mainapp/includes/inc_product_list.html
{% load static i18n %}

{% if obj_pages %}
    {% for object_list in obj_pages %}
        <div class="index-page">
            {% include 'mainapp/includes/inc_index_products.html' %}
        </div>
    {% endfor %}
{% endif %}

geekshop/mainapp/templates/mainapp/includes/inc_product_not_exists.html
{% load static i18n %}

<div class="not_exists">
    <p>{% trans 'Product temporarily not exists on stock' %}</p>
    <a href="{% url 'mainapp:products_category' object.category.id %}">{% trans 'Please, choose another product' %}</a>
</div>